plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.kotlinSerialization)
    alias(libs.plugins.kotest)
    alias(libs.plugins.ksp)
    alias(libs.plugins.ktlint)
}

group = "com.ternbusty"
version = "1.0-SNAPSHOT"

repositories {
    mavenCentral()
}

// Detect if this is a release build
fun isReleaseTask(): Boolean =
    gradle.startParameter.taskNames.any {
        it.contains("Release", ignoreCase = true)
    }

// Provider for generated source directory
val buildConfigDir = layout.buildDirectory.dir("generated/buildconfig")

// Generate BuildConfig.kt with build-time constants.
// Gradle 9 deprecates the `by tasks.registering` property-delegate idiom in
// favour of `tasks.register("name") { ... }` returning a TaskProvider.
val generateBuildConfig = tasks.register("generateBuildConfig") {
    val isRelease = isReleaseTask()
    val defaultLogLevel = if (isRelease) "INFO" else "DEBUG"

    // Track build type as input to invalidate cache when it changes
    inputs.property("buildType", if (isRelease) "release" else "debug")

    // Declare outputs using Provider to wire task dependencies
    outputs.dir(buildConfigDir)

    doLast {
        val outputDir = buildConfigDir.get().asFile
        outputDir.mkdirs()
        file("${outputDir.path}/BuildConfig.kt").writeText(
            """
            package config

            /**
             * Build configuration constants
             * Auto-generated by Gradle build
             */
            object BuildConfig {
                const val DEFAULT_LOG_LEVEL = "$defaultLogLevel"
            }
            """.trimIndent(),
        )
    }
}

// Build C bootstrap library. Gradle 9 removed Project.exec() / Project.copy()
// from inside task actions — the old `doLast { exec { ... } }` block no longer
// compiles. Split into three sequential tasks (compile, archive, stage).
val compileBootstrap = tasks.register<Exec>("compileBootstrap") {
    workingDir = file("src/nativeInterop/cinterop/bootstrap")
    doFirst { file("${workingDir}/build").mkdirs() }
    commandLine(
        "gcc",
        "-c",
        "-fPIC",
        "-Wall",
        "-Wextra",
        "bootstrap.c",
        "-o",
        "build/bootstrap.o",
    )
}

val archiveBootstrap = tasks.register<Exec>("archiveBootstrap") {
    dependsOn(compileBootstrap)
    workingDir = file("src/nativeInterop/cinterop/bootstrap")
    commandLine(
        "ar",
        "rcs",
        "build/libbootstrap.a",
        "build/bootstrap.o",
    )
}

// Stages the archived static library where the cinterop step expects to find it.
val buildBootstrap = tasks.register<Copy>("buildBootstrap") {
    dependsOn(archiveBootstrap)
    from("src/nativeInterop/cinterop/bootstrap/build/libbootstrap.a")
    into(layout.buildDirectory.dir("bootstrap"))
}

kotlin {
    val hostOs = System.getProperty("os.name")
    val isArm64 = System.getProperty("os.arch") == "aarch64"
    val nativeTarget =
        when {
            hostOs == "Linux" && !isArm64 -> linuxX64()
            else -> throw GradleException("Host OS is not supported in Kotlin/Native.")
        }

    nativeTarget.apply {
        binaries {
            executable {
                entryPoint = "main"
                baseName = "kontainer-runtime"
            }
        }

        compilations.getByName("main").cinterops {
            create("libseccomp")
            create("socket")
            create("sched")
            create("closerange")
            create("capability")
            create("bootstrap")
            create("prlimit")
            create("network")
        }
    }

    sourceSets {
        nativeMain {
            dependencies {
                implementation(libs.kotlinxSerializationJson)
                implementation(libs.kotlinxCli)
            }
            // Add generated BuildConfig to source set using Provider
            kotlin.srcDir(buildConfigDir)
        }
        nativeTest.dependencies {
            implementation(libs.kotestAssertionsCore)
            implementation(libs.kotestFrameworkEngine)
        }
    }

    // Ensure BuildConfig is generated before compilation
    targets.withType<org.jetbrains.kotlin.gradle.plugin.mpp.KotlinNativeTarget> {
        compilations["main"].compileTaskProvider.configure {
            dependsOn(generateBuildConfig)
        }
    }
}

// Ensure ktlint tasks run after generation if they touch generated sources
tasks.withType<org.jlleitschuh.gradle.ktlint.tasks.KtLintCheckTask>().configureEach {
    dependsOn(generateBuildConfig)
}
tasks.withType<org.jlleitschuh.gradle.ktlint.tasks.KtLintFormatTask>().configureEach {
    dependsOn(generateBuildConfig)
}

// kotest 6.2+ made the `kotest` Gradle task opt-in: customGradleTask must be set,
// otherwise the plugin throws "property has no value available" at task lookup time.
// We use `./gradlew kotest` in CI, so opt in.
kotest {
    customGradleTask.set(true)
}

ktlint {
    version.set("1.7.1")
    verbose.set(true)
    reporters {
        reporter(org.jlleitschuh.gradle.ktlint.reporter.ReporterType.CHECKSTYLE)
    }
    // Exclude all generated sources without using deprecated buildDir getter
    filter {
        val genRoot =
            layout.buildDirectory
                .dir("generated")
                .get()
                .asFile
                .toPath()
        exclude { it.file.toPath().startsWith(genRoot) }
    }
}

// Ensure bootstrap C library is built before cinterop
tasks.named("cinteropBootstrapLinuxX64") {
    dependsOn(buildBootstrap)
}
