plugins {
    alias(libs.plugins.kotlinMultiplatform)
    alias(libs.plugins.kotlinSerialization)
    alias(libs.plugins.kotest)
    alias(libs.plugins.ksp)
    alias(libs.plugins.ktlint)
}

group = "com.ternbusty"
version = "1.2.4"

repositories {
    mavenCentral()
}

// Detect if this is a release build
fun isReleaseTask(): Boolean =
    gradle.startParameter.taskNames.any {
        it.contains("Release", ignoreCase = true)
    }

// Provider for generated source directory
val buildConfigDir = layout.buildDirectory.dir("generated/buildconfig")

// Generate BuildConfig.kt with build-time constants.
// Gradle 9 deprecates the `by tasks.registering` property-delegate idiom in
// favour of `tasks.register("name") { ... }` returning a TaskProvider.
val generateBuildConfig =
    tasks.register("generateBuildConfig") {
        val isRelease = isReleaseTask()
        val defaultLogLevel = if (isRelease) "ERROR" else "ERROR"

        // Track build type as input to invalidate cache when it changes
        inputs.property("buildType", if (isRelease) "release" else "debug")

        // Declare outputs using Provider to wire task dependencies
        outputs.dir(buildConfigDir)

        doLast {
            val outputDir = buildConfigDir.get().asFile
            outputDir.mkdirs()
            val projectVersion = project.version.toString()
            val gitCommit =
                try {
                    providers
                        .exec { commandLine("git", "rev-parse", "--short", "HEAD") }
                        .standardOutput
                        .asText
                        .get()
                        .trim()
                } catch (_: Exception) {
                    "unknown"
                }
            file("${outputDir.path}/BuildConfig.kt").writeText(
                """
                package config

                /**
                 * Build configuration constants
                 * Auto-generated by Gradle build
                 */
                object BuildConfig {
                    const val DEFAULT_LOG_LEVEL = "$defaultLogLevel"
                    const val VERSION = "$projectVersion"
                    const val COMMIT = "$gitCommit"
                    const val OCI_SPEC_VERSION = "1.0.0"
                }
                """.trimIndent(),
            )
        }
    }

// Detect host architecture for cross-compilation support.
// When targeting linuxArm64 from an x86_64 host, the bootstrap C library must
// be compiled with the aarch64 cross-compiler and libseccomp must be found
// under the aarch64 multilib prefix.
val hostArch: String = System.getProperty("os.arch")
val targetArch: String = (findProperty("targetArch") as? String) ?: hostArch
val crossPrefix = if (targetArch in listOf("aarch64", "arm64")) "aarch64-linux-gnu-" else ""

// Build C bootstrap library. Gradle 9 removed Project.exec() / Project.copy()
// from inside task actions — the old `doLast { exec { ... } }` block no longer
// compiles. Split into three sequential tasks (compile, archive, stage).
// When cross-compiling for aarch64, use the cross-compiler toolchain.
val compileBootstrap =
    tasks.register<Exec>("compileBootstrap") {
        workingDir = file("src/nativeInterop/cinterop/bootstrap")
        doFirst { file("$workingDir/build").mkdirs() }
        commandLine(
            "${crossPrefix}gcc",
            "-c",
            "-fPIC",
            "-Wall",
            "-Wextra",
            "bootstrap.c",
            "-o",
            "build/bootstrap.o",
        )
    }

val archiveBootstrap =
    tasks.register<Exec>("archiveBootstrap") {
        dependsOn(compileBootstrap)
        workingDir = file("src/nativeInterop/cinterop/bootstrap")
        commandLine(
            "${crossPrefix}ar",
            "rcs",
            "build/libbootstrap.a",
            "build/bootstrap.o",
        )
    }

// Stages the archived static library where the cinterop step expects to find it.
val buildBootstrap =
    tasks.register<Copy>("buildBootstrap") {
        dependsOn(archiveBootstrap)
        from("src/nativeInterop/cinterop/bootstrap/build/libbootstrap.a")
        into(layout.buildDirectory.dir("bootstrap"))
    }

// Must stay above the kotlin {} block: the io.kotest plugin reads this flag
// eagerly while targets are created. Set below, the `kotest` task silently
// loses its dependency on linuxX64Test and runs zero tests.
kotest {
    customGradleTask.set(true)
}

// The kotest plugin force-disables Gradle's failOnNoDiscoveredTests on every
// test task from its own taskGraph.whenReady hook. Re-enable it afterwards so
// a test binary with zero registered specs fails the build instead of passing.
gradle.taskGraph.whenReady {
    tasks.withType<org.gradle.api.tasks.testing.AbstractTestTask>().configureEach {
        if (hasProperty("failOnNoDiscoveredTests")) {
            setProperty("failOnNoDiscoveredTests", true)
        }
    }
}

kotlin {
    val hostOs = System.getProperty("os.name")
    if (hostOs != "Linux") {
        throw GradleException("Host OS '$hostOs' is not supported. Only Linux is supported.")
    }

    // Register the appropriate target. When cross-compiling for arm64
    // (via -PtargetArch=aarch64), the Kotlin/Native compiler produces
    // a linuxArm64 binary from the x86_64 host.
    val nativeTarget =
        when (targetArch) {
            "aarch64", "arm64" -> linuxArm64()
            else -> linuxX64()
        }

    // Multilib triplet for architecture-appropriate include/lib paths.
    val triple =
        if (nativeTarget.name == "linuxArm64") {
            "aarch64-linux-gnu"
        } else {
            "x86_64-linux-gnu"
        }

    nativeTarget.apply {
        binaries {
            executable {
                entryPoint = "main"
                baseName = "kontainer-runtime"
            }
        }

        // linkerOpts in a .def file is the canonical way to pass flags to
        // the final link, but it cannot vary by target architecture. Apply
        // them on every compilation (main + test) so the value follows the
        // active target.
        compilations.configureEach {
            compileTaskProvider.configure {
                compilerOptions.freeCompilerArgs.addAll(
                    "-linker-option",
                    "-L/usr/lib/$triple",
                    "-linker-option",
                    "-lseccomp",
                )
            }
        }

        compilations.getByName("main").cinterops {
            create("libseccomp") {
                extraOpts("-compiler-option", "-I/usr/include")
                extraOpts("-compiler-option", "-I/usr/include/$triple")
            }
            create("socket")
            create("sched")
            create("closerange")
            create("capability")
            create("bootstrap")
            create("prlimit")
            create("network")
            create("bpf")
            create("pty")
        }
    }

    sourceSets {
        nativeMain {
            dependencies {
                implementation(libs.kotlinxSerializationJson)
                implementation(libs.clikt)
            }
            // Add generated BuildConfig to source set using Provider
            kotlin.srcDir(buildConfigDir)
        }
        nativeTest.dependencies {
            implementation(libs.kotestAssertionsCore)
            implementation(libs.kotestFrameworkEngine)
        }
    }

    // Ensure BuildConfig is generated before compilation
    nativeTarget.compilations.getByName("main").compileTaskProvider.configure {
        dependsOn(generateBuildConfig)
    }
}

// Ensure ktlint tasks run after generation if they touch generated sources
tasks.withType<org.jlleitschuh.gradle.ktlint.tasks.KtLintCheckTask>().configureEach {
    dependsOn(generateBuildConfig)
}
tasks.withType<org.jlleitschuh.gradle.ktlint.tasks.KtLintFormatTask>().configureEach {
    dependsOn(generateBuildConfig)
}

ktlint {
    version.set("1.7.1")
    verbose.set(true)
    reporters {
        reporter(org.jlleitschuh.gradle.ktlint.reporter.ReporterType.CHECKSTYLE)
    }
    // Exclude all generated sources without using deprecated buildDir getter
    filter {
        val genRoot =
            layout.buildDirectory
                .dir("generated")
                .get()
                .asFile
                .toPath()
        exclude { it.file.toPath().startsWith(genRoot) }
    }
}

// Ensure bootstrap C library is built before cinterop.
// The task name depends on the active Kotlin/Native target (e.g.
// cinteropBootstrapLinuxX64 or cinteropBootstrapLinuxArm64).
tasks.matching { it.name.matches(Regex("cinteropBootstrap(LinuxX64|LinuxArm64)")) }.configureEach {
    dependsOn(buildBootstrap)
}
