package cgroup

import kotlinx.cinterop.ExperimentalForeignApi
import kotlinx.cinterop.addressOf
import kotlinx.cinterop.usePinned
import logger.Logger
import platform.linux._NR_bpf
import platform.posix.O_DIRECTORY
import platform.posix.O_RDONLY
import platform.posix.close
import platform.posix.errno
import platform.posix.open
import platform.posix.syscall
import spec.LinuxDeviceCgroup

/**
 * Attach an eBPF program of type BPF_PROG_TYPE_CGROUP_DEVICE to a
 * container's cgroup directory. The program enforces the access rules
 * from spec.linux.resources.devices.
 *
 * The generated bytecode iterates over the rule list. Each rule compares
 * the incoming (type, access, major, minor) tuple and short-circuits to
 * return its own allow/deny decision; non-matching rules fall through.
 *
 * BPF input layout (from include/uapi/linux/bpf.h):
 *
 *     struct bpf_cgroup_dev_ctx {
 *         __u32 access_type;   // (BPF_DEVCG_ACC_* << 16) | BPF_DEVCG_DEV_*
 *         __u32 major;
 *         __u32 minor;
 *     };
 *
 * Output: R0 = 1 to allow, 0 to deny.
 *
 * Reference: runc libcontainer/cgroups/devices/ebpf.go.
 */
object DeviceCgroup {
    // bpf(2) commands
    private const val BPF_PROG_LOAD = 5
    private const val BPF_PROG_ATTACH = 8

    private const val BPF_PROG_TYPE_CGROUP_DEVICE = 15
    private const val BPF_CGROUP_DEVICE = 6

    // BPF instruction opcodes (subset)
    private const val BPF_LDX_MEM_W = 0x61 // BPF_LDX | BPF_MEM | BPF_W
    private const val BPF_ALU_MOV_K = 0xb7 // BPF_ALU64 | BPF_MOV | BPF_K
    private const val BPF_ALU_MOV_X = 0xbf // BPF_ALU64 | BPF_MOV | BPF_X
    private const val BPF_ALU_RSH_K = 0x77 // BPF_ALU64 | BPF_RSH | BPF_K
    private const val BPF_ALU_AND_K = 0x57 // BPF_ALU64 | BPF_AND | BPF_K
    private const val BPF_JMP_JNE_K = 0x55 // BPF_JMP | BPF_JNE | BPF_K
    private const val BPF_EXIT_INSN = 0x95 // BPF_JMP | BPF_EXIT

    // Device cgroup access bits
    private const val BPF_DEVCG_ACC_MKNOD = 0x1
    private const val BPF_DEVCG_ACC_READ = 0x2
    private const val BPF_DEVCG_ACC_WRITE = 0x4

    // Device cgroup type bits
    private const val BPF_DEVCG_DEV_BLOCK = 0x1
    private const val BPF_DEVCG_DEV_CHAR = 0x2

    /** Default allowed devices appended to every program (runc parity).
     *  See runc libcontainer/specconv/spec_linux.go AllowedDevices. */
    private val DEFAULT_ALLOWED_DEVICES =
        listOf(
            // Wildcard mknod-allow: permit mknod for ANY char/block device.
            // This matches runc's AllowedDevices which always allows mknod
            // even when the spec has a deny-all resources.devices rule.
            allowRule("c", null, null, "m"), // allow mknod for any char device
            allowRule("b", null, null, "m"), // allow mknod for any block device
            // Default device allows (rwm)
            allowRule("c", 1L, 3L, "rwm"), // /dev/null
            allowRule("c", 1L, 5L, "rwm"), // /dev/zero
            allowRule("c", 1L, 7L, "rwm"), // /dev/full
            allowRule("c", 1L, 8L, "rwm"), // /dev/random
            allowRule("c", 1L, 9L, "rwm"), // /dev/urandom
            allowRule("c", 5L, 0L, "rwm"), // /dev/tty
            allowRule("c", 5L, 1L, "rwm"), // /dev/console
            allowRule("c", 5L, 2L, "rwm"), // /dev/ptmx
            allowRule("c", 136L, null, "rwm"), // pts/* (major 136, any minor)
        )

    private fun allowRule(
        type: String,
        major: Long?,
        minor: Long?,
        access: String,
    ) = LinuxDeviceCgroup(
        allow = true,
        type = type,
        major = major,
        minor = minor,
        access = access,
    )

    /**
     * Build, load, and attach the eBPF device-cgroup program.
     *
     * @param cgroupDirPath absolute filesystem path to the cgroup directory
     *                      (e.g. `/sys/fs/cgroup/kontainer-runtime/mycontainer`)
     * @param rules device rules from spec.linux.resources.devices
     */
    @OptIn(ExperimentalForeignApi::class)
    fun apply(
        cgroupDirPath: String,
        rules: List<LinuxDeviceCgroup>,
    ) {
        // Process user rules first, then default device allows.
        // The emulator resolves the final state: default action +
        // exception list. This matches runc's approach where default
        // devices are appended AFTER user rules.
        val effective = rules + DEFAULT_ALLOWED_DEVICES
        val prog = buildProgram(effective)
        Logger.debug("built cgroup_device bpf program, ${prog.size / 8} insns")

        val progFd = loadProgram(prog)
        if (progFd < 0) {
            Logger.warn("bpf_prog_load failed (errno=$errno)")
            return
        }

        try {
            val cgFd = open(cgroupDirPath, O_RDONLY or O_DIRECTORY)
            if (cgFd < 0) {
                Logger.warn("failed to open cgroup dir $cgroupDirPath (errno=$errno)")
                return
            }
            try {
                if (attachProgram(cgFd, progFd) != 0) {
                    Logger.warn("bpf_prog_attach failed (errno=$errno)")
                } else {
                    Logger.info("device cgroup bpf program attached to $cgroupDirPath")
                }
            } finally {
                close(cgFd)
            }
        } finally {
            close(progFd)
        }
    }

    // ---- Device emulator (mirrors runc's devices_emulator.go) ----

    /**
     * Emulated device cgroup state: a default action plus a list of
     * exceptions.  Mirrors runc's Emulator from
     * libcontainer/cgroups/devices/devices_emulator.go.
     */
    internal data class EmulatedState(
        val defaultAllow: Boolean,
        val exceptions: List<LinuxDeviceCgroup>,
    )

    /**
     * Process rules in order through the emulator to produce a final
     * (default, exceptions) state.  Wildcard rules (type=null/"a") reset
     * the default and clear exceptions.  Specific rules that differ from
     * the current default are added as exceptions; rules that match the
     * default are no-ops (but may remove a prior conflicting exception).
     */
    internal fun emulate(rules: List<LinuxDeviceCgroup>): EmulatedState {
        var defaultAllow = false
        val exceptions = mutableListOf<LinuxDeviceCgroup>()

        for (rule in rules) {
            if (rule.type == null || rule.type == "" || rule.type == "a") {
                // Wildcard rule — set default and clear all exceptions
                defaultAllow = rule.allow
                exceptions.clear()
            } else {
                // Specific rule — remove any existing exception for the
                // same (type, major, minor) and if this rule differs from
                // the default, add it as an exception.
                exceptions.removeAll { ex ->
                    ex.type == rule.type && ex.major == rule.major && ex.minor == rule.minor
                }
                if (rule.allow != defaultAllow) {
                    exceptions.add(rule)
                }
            }
        }
        return EmulatedState(defaultAllow, exceptions)
    }

    // ---- BPF bytecode emitter (package-visible for testing) ----

    /**
     * Build the BPF program for the given device rules.
     * First emulates the rule list to determine the default action and
     * exception list, then generates BPF that checks exceptions before
     * falling through to the default.
     * Visible internally so unit tests can assert on the bytecode.
     */
    internal fun buildProgram(rules: List<LinuxDeviceCgroup>): ByteArray {
        val state = emulate(rules)
        val out = mutableListOf<Byte>()

        // 6-instruction prelude: load ctx fields into registers.
        //   R2 = *(u32 *)(R1+0)  — access_type
        //   R3 = R2              — copy
        //   R3 = R3 >> 16        — access bits
        //   R2 = R2 & 0xFFFF     — device type
        //   R5 = *(u32 *)(R1+4)  — major
        //   R6 = *(u32 *)(R1+8)  — minor
        emit(out, BPF_LDX_MEM_W, 2, 1, 0, 0)
        emit(out, BPF_ALU_MOV_X, 3, 2, 0, 0)
        emit(out, BPF_ALU_RSH_K, 3, 0, 0, 16)
        emit(out, BPF_ALU_AND_K, 2, 0, 0, 0xFFFF)
        emit(out, BPF_LDX_MEM_W, 5, 1, 4, 0)
        emit(out, BPF_LDX_MEM_W, 6, 1, 8, 0)

        // Per-exception branch chains.  Each exception is the OPPOSITE
        // of the default (if default=deny, exceptions are allows, and
        // vice versa).
        for (r in state.exceptions) {
            val devType = parseDevType(r.type)
            val accBits = parseAccessBits(r.access)

            val sub = mutableListOf<Byte>()

            if (devType != 0) {
                emit(sub, BPF_JMP_JNE_K, 2, 0, 0, devType)
            }
            if (accBits != 0) {
                // R7 = R3; R7 &= ~accBits; if R7 != 0 → skip (extra access bits requested)
                emit(sub, BPF_ALU_MOV_X, 7, 3, 0, 0)
                emit(sub, BPF_ALU_AND_K, 7, 0, 0, accBits.inv())
                emit(sub, BPF_JMP_JNE_K, 7, 0, 0, 0)
            }
            if (r.major != null) {
                emit(sub, BPF_JMP_JNE_K, 5, 0, 0, r.major.toInt())
            }
            if (r.minor != null) {
                emit(sub, BPF_JMP_JNE_K, 6, 0, 0, r.minor.toInt())
            }
            // Match: return exception's action (opposite of default).
            emit(sub, BPF_ALU_MOV_K, 0, 0, 0, if (r.allow) 1 else 0)
            emit(sub, BPF_EXIT_INSN, 0, 0, 0, 0)

            val subBytes = sub.toByteArray()
            val totalInsns = subBytes.size / 8
            patchJumps(subBytes, totalInsns)
            out.addAll(subBytes.toList())
        }

        // Default tail: return the emulated default action.
        emit(out, BPF_ALU_MOV_K, 0, 0, 0, if (state.defaultAllow) 1 else 0)
        emit(out, BPF_EXIT_INSN, 0, 0, 0, 0)

        return out.toByteArray()
    }

    /**
     * Patch every JNE in the block to jump past the trailing exit instruction,
     * falling into the next rule or the default tail.
     */
    private fun patchJumps(
        block: ByteArray,
        totalInsns: Int,
    ) {
        for (i in 0 until totalInsns) {
            val base = i * 8
            val code = block[base].toInt() and 0xFF
            if (code == BPF_JMP_JNE_K) {
                val newOff = totalInsns - 1 - i
                block[base + 2] = (newOff and 0xFF).toByte()
                block[base + 3] = ((newOff shr 8) and 0xFF).toByte()
            }
        }
    }

    private fun parseDevType(type: String?): Int =
        when (type) {
            null, "", "a" -> 0
            "c", "u" -> BPF_DEVCG_DEV_CHAR
            "b" -> BPF_DEVCG_DEV_BLOCK
            else -> 0
        }

    private fun parseAccessBits(access: String?): Int {
        if (access == null) return 0
        var b = 0
        if ('r' in access) b = b or BPF_DEVCG_ACC_READ
        if ('w' in access) b = b or BPF_DEVCG_ACC_WRITE
        if ('m' in access) b = b or BPF_DEVCG_ACC_MKNOD
        return b
    }

    private fun emit(
        out: MutableList<Byte>,
        opcode: Int,
        dstReg: Int,
        srcReg: Int,
        off: Int,
        imm: Int,
    ) {
        out.add(opcode.toByte())
        out.add((((srcReg and 0xF) shl 4) or (dstReg and 0xF)).toByte())
        out.add((off and 0xFF).toByte())
        out.add(((off shr 8) and 0xFF).toByte())
        out.add((imm and 0xFF).toByte())
        out.add(((imm shr 8) and 0xFF).toByte())
        out.add(((imm shr 16) and 0xFF).toByte())
        out.add(((imm shr 24) and 0xFF).toByte())
    }

    // ---- BPF syscall wrappers ----

    /** Encode a little-endian u32 into [buf] at [offset]. */
    private fun putU32(
        buf: ByteArray,
        offset: Int,
        value: Int,
    ) {
        buf[offset] = (value and 0xFF).toByte()
        buf[offset + 1] = ((value shr 8) and 0xFF).toByte()
        buf[offset + 2] = ((value shr 16) and 0xFF).toByte()
        buf[offset + 3] = ((value shr 24) and 0xFF).toByte()
    }

    /** Encode a little-endian u64 into [buf] at [offset]. */
    private fun putU64(
        buf: ByteArray,
        offset: Int,
        value: ULong,
    ) {
        for (i in 0 until 8) {
            buf[offset + i] = ((value shr (i * 8)) and 0xFFu).toByte()
        }
    }

    /**
     * Call bpf(BPF_PROG_LOAD, ...) to load the device cgroup program.
     * Returns the prog FD on success, -1 on error (errno is set).
     */
    @OptIn(ExperimentalForeignApi::class)
    private fun loadProgram(prog: ByteArray): Int {
        // union bpf_attr layout for BPF_PROG_LOAD:
        //   offset  0: u32 prog_type
        //   offset  4: u32 insn_cnt
        //   offset  8: u64 insns     (aligned pointer)
        //   offset 16: u64 license   (aligned pointer)
        // Total size: at least 128 bytes to be safe for all kernel versions.
        val attrSize = 128
        val attr = ByteArray(attrSize)
        putU32(attr, 0, BPF_PROG_TYPE_CGROUP_DEVICE)
        putU32(attr, 4, prog.size / 8)

        return prog.usePinned { pinnedProg ->
            val licenseBytes = "GPL ".encodeToByteArray()
            licenseBytes.usePinned { pinnedLicense ->
                val insnsPtr =
                    pinnedProg
                        .addressOf(0)
                        .rawValue
                        .toLong()
                        .toULong()
                putU64(attr, 8, insnsPtr)
                val licensePtr =
                    pinnedLicense
                        .addressOf(0)
                        .rawValue
                        .toLong()
                        .toULong()
                putU64(attr, 16, licensePtr)

                attr.usePinned { pinnedAttr ->
                    syscall(
                        _NR_bpf(),
                        BPF_PROG_LOAD.toLong(),
                        pinnedAttr.addressOf(0),
                        attrSize.toLong(),
                    ).toInt()
                }
            }
        }
    }

    /**
     * Call bpf(BPF_PROG_ATTACH, ...) to attach the device program to the cgroup.
     * Returns 0 on success, -1 on error.
     */
    @OptIn(ExperimentalForeignApi::class)
    private fun attachProgram(
        cgroupFd: Int,
        progFd: Int,
    ): Int {
        // union bpf_attr layout for BPF_PROG_ATTACH:
        //   offset 0: u32 target_fd
        //   offset 4: u32 attach_bpf_fd
        //   offset 8: u32 attach_type
        //   offset 12: u32 attach_flags
        val attrSize = 64
        val attr = ByteArray(attrSize)
        putU32(attr, 0, cgroupFd)
        putU32(attr, 4, progFd)
        putU32(attr, 8, BPF_CGROUP_DEVICE)
        putU32(attr, 12, 0)

        return attr.usePinned { pinnedAttr ->
            syscall(
                _NR_bpf(),
                BPF_PROG_ATTACH.toLong(),
                pinnedAttr.addressOf(0),
                attrSize.toLong(),
            ).toInt()
        }
    }
}
